### ISSUE TITLE
Content Policy

### ISSUE THREAD

**Issue by TerapistBilgisayar** [frogermcs/InstaMaterial#21]
Hi ,

I use instaMaterial app . I developed it and change lots of things. When I loaded it to Google Play Store , it gave me an eror. This app is impersonates  İnstagram . Has anyone else encountered this error? Or do you have any suggestion  for this problem? 

Thanks ,

**Comment by DatzZDeVesh** [comment]
have you solved with the issues. please let me know !

**Comment by gdaelexxer** [comment]
not yet solved what i wanted yet datz and i could need your help in
creating my application are you willing to help?

**Comment by DatzZDeVesh** [comment]
yes sure will get time than surely will help you. my skype is "devesh.balwani"

**Comment by gdaelexxer** [comment]
thank you sir i appreciate i have an idea and it seems amazing..... we can
patner on this so that can create an amazing app and change the world

**Comment by vojo28** [comment]
Hello please where u able to bypass this problem and it seems u are quite a pro in android i would like you to help explain some useful bit of information to me .Thanks
